version: '3'

services:
  app-service:
    build: ./app-service
    container_name: app-service
    restart: always
    
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    environment:
      - SERVER_NAME=zoho.automatedtaxcredits.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/zoho.automatedtaxcredits.com/fullchain.pem:/etc/letsencrypt/live/zoho.automatedtaxcredits.com/fullchain.pem:ro
      - /etc/letsencrypt/live/zoho.automatedtaxcredits.com/privkey.pem:/etc/letsencrypt/live/zoho.automatedtaxcredits.com/privkey.pem:ro
